services:
  - type: web
    name: fasal-ai
    env: python
    plan: free            # or 'starter' / 'standard' / etc.
    region: oregon        # or 'frankfurt' if you prefer EU
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --threads=4 --timeout=120
    envVars:
      - key: OWM_API_KEY
        sync: false       # set in dashboard (don’t commit your secret)
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: BABEL_DEFAULT_LOCALE
        value: en
    autoDeploy: true
    routes:
      - type: rewrite
        source: /.*
        destination: /
